-- Script pour remplacer "CodePlus" par "Revival" dans le texte affiché aux utilisateurs
-- Exécuter ce script dans phpMyAdmin ou en ligne de commande MySQL
-- NE MODIFIE QUE LE CONTENU AFFICHÉ - N'IMPACTE PAS LE SYSTÈME

-- 1. Nom du site (header, footer, emails, etc.)
UPDATE general_settings SET site_name = 'Revival' WHERE site_name = 'CodePlus';

-- 2. Contenu frontend (bannière, login, register, CTA, SEO, politiques, etc.)
UPDATE frontends SET data_values = REPLACE(data_values, 'CodePlus', 'Revival') WHERE data_values LIKE '%CodePlus%';
UPDATE frontends SET data_values = REPLACE(data_values, '"codeplus"', '"Revival"') WHERE data_values LIKE '%"codeplus"%';
UPDATE frontends SET data_values = REPLACE(data_values, 'support@CodePlus.com', 'support@Revival.com') WHERE data_values LIKE '%support@CodePlus.com%';

-- 3. Traduction FR des pages de politique
UPDATE frontends
SET data_values = JSON_OBJECT(
    'title', 'Politique de confidentialite',
    'details', '<div><h6 class="mb-1">Quelles informations collectons-nous ?</h6><p>Nous recueillons certaines donnees lorsque vous vous inscrivez sur notre site, soumettez une demande, sollicitez une assistance ou remplissez un formulaire. Selon le cas, il peut vous etre demande de renseigner votre nom, votre adresse e-mail ou votre numero de telephone. Vous pouvez toutefois visiter notre site de maniere anonyme.</p><p><br /></p></div><div><h6 class="mb-1">Comment protegeons-nous vos informations ?</h6><p>Les donnees sensibles ou bancaires transmises via nos prestataires de paiement sont protegees pendant leur transfert.<br />Apres la transaction, vos donnees privees, comme les numeros de carte, identifiants officiels ou informations financieres, ne sont pas stockees de maniere non securisee sur notre infrastructure.</p><p><br /></p></div><div><h6 class="mb-1">Communiquons-nous vos informations a des tiers ?</h6><p>Nous ne vendons pas, n''echangeons pas et ne transferons pas vos donnees personnelles a des tiers, sauf aux prestataires de confiance qui nous aident a exploiter le site, fournir nos services ou vous assister, a condition qu''ils respectent la confidentialite de ces informations. Nous pouvons egalement divulguer certaines donnees si la loi nous y oblige, pour faire respecter nos politiques ou pour proteger nos droits, nos biens ou notre securite ainsi que ceux des autres.</p><p><br /></p></div><div><h6 class="mb-1">Protection de la vie privee des mineurs</h6><p>Nous respectons les exigences applicables en matiere de protection des enfants en ligne. Nous ne collectons pas sciemment de donnees concernant des personnes de moins de 13 ans. Notre site et nos services sont destines a des utilisateurs ages de 13 ans ou plus.</p><p><br /></p></div><div><h6 class="mb-1">Modifications de cette politique</h6><p>Si nous modifions notre politique de confidentialite, les changements seront publies sur cette page.</p><p><br /></p></div><div><h6 class="mb-1">Duree de conservation de vos donnees</h6><p>Lorsque vous creez un compte sur notre site, nous conservons les informations necessaires aussi longtemps que votre compte reste actif ou aussi longtemps que la loi nous y oblige.</p><p><br /></p></div><div><h6 class="mb-1">Ce que nous ne faisons pas avec vos donnees</h6><p>Nous ne partageons pas, ne vendons pas et ne cedons jamais vos donnees a d''autres entreprises pour la promotion de leurs produits ou services.</p></div>'
)
WHERE data_keys = 'policy_pages.element' AND slug = 'privacy-policy';

UPDATE frontends
SET data_values = JSON_OBJECT(
    'title', 'Conditions d''utilisation',
    'details', '<div><h6 class="mb-1">Conditions generales pour les utilisateurs</h6><p>En accedant a ce site, vous acceptez d''etre lie par les presentes conditions d''utilisation, ainsi que par les lois et reglementations applicables. Vous reconnaissez etre responsable du respect de toute regle locale applicable. Si vous n''acceptez pas ces conditions, vous ne devez pas utiliser ce site.</p><p><br /></p></div><div><h6 class="mb-1">Assistance</h6><p>Si vous avez besoin d''aide concernant nos services ou nos contenus, vous pouvez contacter notre equipe par e-mail ou via les canaux de support disponibles sur la plateforme. Nous faisons notre possible pour traiter les demandes dans des delais raisonnables.</p><p>Si votre demande necessite une adaptation plus poussee de la plateforme, plusieurs options peuvent vous etre proposees : attendre une prochaine mise a jour ou solliciter une intervention specifique si ce service est disponible.</p></div><div><h6 class="mb-1">Propriete intellectuelle</h6><p>Vous ne pouvez pas revendiquer la propriete intellectuelle exclusive de nos produits, contenus ou services, qu''ils soient modifies ou non. Sauf mention contraire, ces elements restent la propriete de leurs auteurs ou de la plateforme. Ils sont fournis en l''etat, sans garantie expresse ou implicite.</p><p><br /></p></div><div><h6 class="mb-1">Garantie</h6><p>Nous ne garantissons pas que les services fonctionneront dans tous les environnements, avec tous les modules tiers ou sur tous les navigateurs. Il vous appartient de verifier la compatibilite avec votre contexte d''utilisation avant de vous engager davantage sur la plateforme.</p><p><br /></p></div><div><h6 class="mb-1">Utilisation interdite ou illegale</h6><p>Vous ne pouvez pas utiliser la plateforme a des fins illegales, non autorisees ou contraires aux lois applicables, notamment en matiere de propriete intellectuelle. Il est strictement interdit de publier, promouvoir ou diffuser des contenus violents, haineux, terroristes, pornographiques, obscenes ou lies a des logiciels pirates.</p><p><br /></p></div><div><h6 class="mb-1">Contenu promotionnel et avantages</h6><p>Nous pouvons proposer a certains moments des avantages promotionnels, credits ou coupons. Nous nous reservons le droit de les examiner, de les ajuster ou de les retirer en cas d''usage abusif, frauduleux ou contraire aux regles de la plateforme.</p></div>'
)
WHERE data_keys = 'policy_pages.element' AND slug = 'terms-of-service';

UPDATE frontends
SET data_values = JSON_OBJECT(
    'title', 'Politique de remboursement',
    'details', '<div>Chez <b>Revival</b>, nous faisons le maximum pour proposer un service fiable et une experience utilisateur claire. Si une demande de remboursement est recevable selon nos regles internes ou selon le droit applicable, elle sera etudiee avec attention.</div><div><br /></div><h6>Demande de remboursement :</h6><div>Si vous estimez qu''une situation justifie un remboursement, vous devez contacter notre equipe de support en precisant les details de votre demande, les elements de contexte et toute information utile a son examen.</div><div><br /></div><h6>Conditions d''eligibilite :</h6><div>Une demande peut etre examinee notamment dans les cas suivants :</div><div><br /></div><div>1. Le signalement est effectue dans un delai raisonnable apres la transaction concernee.</div><div>2. Le probleme rencontre est documente de maniere suffisamment precise.</div><div>3. Aucune utilisation abusive, frauduleuse ou contraire a nos conditions n''est constatee.</div><div><br /></div><h6>Traitement de la demande :</h6><div>Chaque demande est analysee au cas par cas. Si un remboursement est valide, il est effectue via le moyen de paiement initial lorsque cela est techniquement possible, ou selon une autre modalite adaptee.</div><div><br /></div><h6>Exceptions :</h6><div>Certaines situations peuvent exclure un remboursement, notamment en cas d''usage abusif, de personnalisation specifique, d''intervention deja executee, ou lorsque la reglementation applicable ne prevoit pas de restitution.</div><div><br /></div><h6>Nous contacter :</h6><div>Pour toute question relative a cette politique, contactez notre equipe de support via les coordonnees affichees sur la plateforme.</div><div><br /></div><h6>Modification de la politique :</h6><div>Nous nous reservons le droit de modifier cette politique a tout moment. Toute mise a jour prend effet des sa publication sur cette page.</div><div><br /></div>'
)
WHERE data_keys = 'policy_pages.element' AND slug = 'refund-policy';
