-- Script pour remplacer "CodePlus" par "Revival" dans le texte affiché aux utilisateurs
-- Exécuter ce script dans phpMyAdmin ou en ligne de commande MySQL
-- NE MODIFIE QUE LE CONTENU AFFICHÉ - N'IMPACTE PAS LE SYSTÈME

-- 1. Nom du site (header, footer, emails, etc.)
UPDATE general_settings SET site_name = 'Revival' WHERE site_name = 'CodePlus';

-- 2. Contenu frontend (bannière, login, register, CTA, SEO, politiques, etc.)
UPDATE frontends SET data_values = REPLACE(data_values, 'CodePlus', 'Revival') WHERE data_values LIKE '%CodePlus%';
UPDATE frontends SET data_values = REPLACE(data_values, '"codeplus"', '"Revival"') WHERE data_values LIKE '%"codeplus"%';
UPDATE frontends SET data_values = REPLACE(data_values, 'support@CodePlus.com', 'support@Revival.com') WHERE data_values LIKE '%support@CodePlus.com%';

-- 3. Traduction FR des pages de politique
UPDATE frontends
SET data_values = '{"title":"Politique de confidentialité","details":"<div><h6 class=\"mb-1\">Quelles informations collectons-nous ?</h6><p>Nous recueillons certaines données lorsque vous vous inscrivez sur notre site, soumettez une demande, sollicitez une assistance ou remplissez un formulaire. Selon le cas, il peut vous être demandé de renseigner votre nom, votre adresse e-mail ou votre numéro de téléphone. Vous pouvez toutefois visiter notre site de manière anonyme.</p><p><br /></p></div><div><h6 class=\"mb-1\">Comment protégeons-nous vos informations ?</h6><p>Les données sensibles ou bancaires transmises via nos prestataires de paiement sont protégées pendant leur transfert.<br />Après la transaction, vos données privées, comme les numéros de carte, identifiants officiels ou informations financières, ne sont pas stockées de manière non sécurisée sur notre infrastructure.</p><p><br /></p></div><div><h6 class=\"mb-1\">Communiquons-nous vos informations à des tiers ?</h6><p>Nous ne vendons pas, n''échangeons pas et ne transférons pas vos données personnelles à des tiers, sauf aux prestataires de confiance qui nous aident à exploiter le site, fournir nos services ou vous assister, à condition qu''ils respectent la confidentialité de ces informations. Nous pouvons également divulguer certaines données si la loi nous y oblige, pour faire respecter nos politiques ou pour protéger nos droits, nos biens ou notre sécurité ainsi que ceux des autres.</p><p><br /></p></div><div><h6 class=\"mb-1\">Protection de la vie privée des mineurs</h6><p>Nous respectons les exigences applicables en matière de protection des enfants en ligne. Nous ne collectons pas sciemment de données concernant des personnes de moins de 13 ans. Notre site et nos services sont destinés à des utilisateurs âgés de 13 ans ou plus.</p><p><br /></p></div><div><h6 class=\"mb-1\">Modifications de cette politique</h6><p>Si nous modifions notre politique de confidentialité, les changements seront publiés sur cette page.</p><p><br /></p></div><div><h6 class=\"mb-1\">Durée de conservation de vos données</h6><p>Lorsque vous créez un compte sur notre site, nous conservons les informations nécessaires aussi longtemps que votre compte reste actif ou aussi longtemps que la loi nous y oblige.</p><p><br /></p></div><div><h6 class=\"mb-1\">Ce que nous ne faisons pas avec vos données</h6><p>Nous ne partageons pas, ne vendons pas et ne cédons jamais vos données à d''autres entreprises pour la promotion de leurs produits ou services.</p></div>"}'
WHERE data_keys = 'policy_pages.element' AND slug = 'privacy-policy';

UPDATE frontends
SET data_values = '{"title":"Conditions d’utilisation","details":"<div><h6 class=\"mb-1\">Conditions générales pour les utilisateurs</h6><p>En accédant à ce site, vous acceptez d''être lié par les présentes conditions d''utilisation, ainsi que par les lois et réglementations applicables. Vous reconnaissez être responsable du respect de toute règle locale applicable. Si vous n''acceptez pas ces conditions, vous ne devez pas utiliser ce site.</p><p><br /></p></div><div><h6 class=\"mb-1\">Assistance</h6><p>Si vous avez besoin d''aide concernant nos services ou nos contenus, vous pouvez contacter notre équipe par e-mail ou via les canaux de support disponibles sur la plateforme. Nous faisons notre possible pour traiter les demandes dans des délais raisonnables.</p><p>Si votre demande nécessite une adaptation plus poussée de la plateforme, plusieurs options peuvent vous être proposées : attendre une prochaine mise à jour ou solliciter une intervention spécifique si ce service est disponible.</p></div><div><h6 class=\"mb-1\">Propriété intellectuelle</h6><p>Vous ne pouvez pas revendiquer la propriété intellectuelle exclusive de nos produits, contenus ou services, qu''ils soient modifiés ou non. Sauf mention contraire, ces éléments restent la propriété de leurs auteurs ou de la plateforme. Ils sont fournis en l''état, sans garantie expresse ou implicite.</p><p><br /></p></div><div><h6 class=\"mb-1\">Garantie</h6><p>Nous ne garantissons pas que les services fonctionneront dans tous les environnements, avec tous les modules tiers ou sur tous les navigateurs. Il vous appartient de vérifier la compatibilité avec votre contexte d''utilisation avant de vous engager davantage sur la plateforme.</p><p><br /></p></div><div><h6 class=\"mb-1\">Utilisation interdite ou illégale</h6><p>Vous ne pouvez pas utiliser la plateforme à des fins illégales, non autorisées ou contraires aux lois applicables, notamment en matière de propriété intellectuelle. Il est strictement interdit de publier, promouvoir ou diffuser des contenus violents, haineux, terroristes, pornographiques, obscènes ou liés à des logiciels piratés.</p><p><br /></p></div><div><h6 class=\"mb-1\">Contenu promotionnel et avantages</h6><p>Nous pouvons proposer à certains moments des avantages promotionnels, crédits ou coupons. Nous nous réservons le droit de les examiner, de les ajuster ou de les retirer en cas d''usage abusif, frauduleux ou contraire aux règles de la plateforme.</p></div>"}'
WHERE data_keys = 'policy_pages.element' AND slug = 'terms-of-service';

UPDATE frontends
SET data_values = '{"title":"Politique de remboursement","details":"<div>Chez <b>Revival</b>, nous faisons le maximum pour proposer un service fiable et une expérience utilisateur claire. Si une demande de remboursement est recevable selon nos règles internes ou selon le droit applicable, elle sera étudiée avec attention.</div><div><br /></div><h6>Demande de remboursement :</h6><div>Si vous estimez qu''une situation justifie un remboursement, vous devez contacter notre équipe de support en précisant les détails de votre demande, les éléments de contexte et toute information utile à son examen.</div><div><br /></div><h6>Conditions d''éligibilité :</h6><div>Une demande peut être examinée notamment dans les cas suivants :</div><div><br /></div><div>1. Le signalement est effectué dans un délai raisonnable après la transaction concernée.</div><div>2. Le problème rencontré est documenté de manière suffisamment précise.</div><div>3. Aucune utilisation abusive, frauduleuse ou contraire à nos conditions n''est constatée.</div><div><br /></div><h6>Traitement de la demande :</h6><div>Chaque demande est analysée au cas par cas. Si un remboursement est validé, il est effectué via le moyen de paiement initial lorsque cela est techniquement possible, ou selon une autre modalité adaptée.</div><div><br /></div><h6>Exceptions :</h6><div>Certaines situations peuvent exclure un remboursement, notamment en cas d''usage abusif, de personnalisation spécifique, d''intervention déjà exécutée, ou lorsque la réglementation applicable ne prévoit pas de restitution.</div><div><br /></div><h6>Nous contacter :</h6><div>Pour toute question relative à cette politique, contactez notre équipe de support via les coordonnées affichées sur la plateforme.</div><div><br /></div><h6>Modification de la politique :</h6><div>Nous nous réservons le droit de modifier cette politique à tout moment. Toute mise à jour prend effet dès sa publication sur cette page.</div><div><br /></div>"}'
WHERE data_keys = 'policy_pages.element' AND slug = 'refund-policy';
